-- Permite ao aluno pedir a eliminação de uma solicitação,
-- aguardando confirmação administrativa.
CREATE TABLE IF NOT EXISTS public.pedidos_eliminacao_apoio (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitacao_id integer NOT NULL,
    utilizador_id integer NOT NULL,
    estado character varying(30) NOT NULL DEFAULT 'pendente',
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    decided_at timestamp without time zone,
    CONSTRAINT pedidos_eliminacao_apoio_solicitacao_id_fkey
        FOREIGN KEY (solicitacao_id) REFERENCES public.solicitacoes_apoio(id) ON DELETE CASCADE,
    CONSTRAINT pedidos_eliminacao_apoio_utilizador_id_fkey
        FOREIGN KEY (utilizador_id) REFERENCES public.utilizadores(id) ON DELETE CASCADE,
    CONSTRAINT pedidos_eliminacao_apoio_estado_check
        CHECK (estado IN ('pendente', 'aceite', 'recusada'))
);

CREATE UNIQUE INDEX IF NOT EXISTS pedidos_eliminacao_apoio_pendente_unico
    ON public.pedidos_eliminacao_apoio (solicitacao_id)
    WHERE estado = 'pendente';
